### PR TITLE
Mode report workaround

### PR DESCRIPTION
**Pull request by process1183**
Addition of a simple flag to correct the off-by-one error for the mode present in the sensor stream of some 6xx Roomba models.

Ref: [github.com/AutonomyLab/create_robot/issues/64](https://github.com/AutonomyLab/create_robot/issues/64)

### CODE REVIEW

**Review by jacobperron — COMMENTED** [review]
Thanks, looks reasonable to me.

Could you add a note about this workaround/API to the README?  The [Known Issues](https://github.com/AutonomyLab/libcreate/blob/master/README.md#known-issues) section seems like a good place.

**Comment by jacobperron** [comment]
Also, feel free to add yourself to the contributors list :)

**Comment by process1183** [comment]
No problem! I've added details regarding the OI mode issue and workaround to the README.

**Comment by jacobperron** [comment]
Thanks for the contribution!

**Pull request merged**
